project:
  type: website

website:
  title: "Weather Analytics"
  image: "images/sunny.png"
  favicon: "images/sunny.png"
  navbar:
    logo: "images/sunny.png"
    title: false
    collapse-below: lg
    background: "#1B264F"
    right:
      - text: "Proposal"
        href: proposal/proposal.html
      - text: Prototyping
        menu:
          - text: Data retrieval and wrangling
            href: code/data_retrieval.html
          - text: Data preparation for Weather
            href: code/Data_preparation_Weather.html
          - text: Prototyping for app modules
            href: code/prototyping.html
      - text: "Shiny App"
        menu:
          - text: "User Guide"
            href: artifacts/userguide.pdf
          - text: "Shiny App"
            href: https://isss608-group9-weatheranalytics.shinyapps.io/shinyapp/
      - text: "Project Poster"
        href: artifacts/poster.pdf
      - text: "The Team"
        href: about.html


format:
  html:
    theme: 
      - theme.scss
    css: styles.css
    toc: true
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap

editor: visual

