project:
  type: website

website:
  title: "Weatherwise or Otherwise"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
      - text: Project Proposal
        href: Project_Proposal.html
      - text: Prototyping
        menu:
          - text: Exploratory Data Analysis
            href: code/EDA.html
      - text: Shiny App
        href: app.html
      - text: Project Poster
        href: project_poster.pdf
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

