---
title: "Weather Analytics"
subtitle: "A Visual Analytics Tool for Singapore's Weather"
---

In Singapore, significant research has been conducted on climate change, highlighting the importance of understanding changing weather patterns. The National Environment Agency in Singapore has made historical weather data accessible, yet there is still a need for user-friendly tools to effectively visualize and analyze this data for a deeper comprehension of its implications. Exploring these datasets within a visual analytics environment can offer invaluable insights for various stakeholders, from policymakers to the general public.

Currently, the available tools for visualizing Singapore’s historical weather data are limited. These existing tools often feature static displays and offer limited analytical depth, failing to capture the complex temporal and spatial nature of the data. Moreover, they lack interactivity and advanced analytical functions, which are crucial for a comprehensive exploration of weather patterns.

To bridge this gap, we aim to develop an interactive R Shiny application designed specifically for the exploration of Singapore’s historical weather data. This tool will enable users to dive deep into the climate aspects, uncovering patterns and insights through a dynamic and engaging visual analytics platform.
